{
 "title": "Grok_FIO_Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "FIO BANDWIDTH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bandwidth_randwrite" },
    { "expr": "bandwidth_randread" },
    { "expr": "bandwidth_seqwrite" },
    { "expr": "bandwidth_seqread" },
    { "expr": "bandwidth_randrw_write" },
    { "expr": "bandwidth_randrw_read" },
    { "expr": "bandwidth_seqrw_write" },
    { "expr": "bandwidth_seqrw_read" }
   ]
  },
  {
   "title": "FIO AVG LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg_latency_randwrite" },
    { "expr": "avg_latency_randread" },
    { "expr": "avg_latency_seqwrite" },
    { "expr": "avg_latency_seqread" },
    { "expr": "avg_latency_randrw_write" },
    { "expr": "avg_latency_seqrw_write" }
   ]
  },
  {
   "title": "FIO IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "iops_randwrite" },
    { "expr": "iops_randread" },
    { "expr": "iops_seqwrite" },
    { "expr": "iops_seqread" },
    { "expr": "iops_randrw_write" },
    { "expr": "iops_randrw_read" },
    { "expr": "iops_seqrw_write" },
    { "expr": "iops_seqrw_read" }
   ]
  }
 ]
}